builds:
- id: dcp
  env:
  - CGO_ENABLED=0
  main: cmd/cloud/dcp/main.go
  binary: dcp
  ldflags:
  - -s -w -X github.com/bhojpur/dcp/pkg/version.Version={{.Version}}-{{.ShortCommit}}
- id: statebase
  env:
  - CGO_ENABLED=0
  main: cmd/cloud/statebase/main.go
  binary: statebase
  ldflags:
  - -s -w -X github.com/bhojpur/dcp/pkg/version.Version={{.Version}}-{{.ShortCommit}}
- id: ctrfyle
  env:
  - CGO_ENABLED=0
  main: cmd/tools/ctrfyle/main.go
  binary: ctrfyle
  ldflags:
  - -s -w -X github.com/bhojpur/dcp/pkg/version.Version={{.Version}}-{{.ShortCommit}}
- id: tunnel-agent
  env:
  - CGO_ENABLED=0
  main: cmd/grid/tunnel-agent.go
  binary: tunnel-agent
  flags:
    - -tags=tunnel-agent
  ldflags:
  - -s -w -X github.com/bhojpur/dcp/pkg/version.version={{.Version}}-{{.ShortCommit}}
archives:
- id: dcp
  builds:
  - dcp
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
- id: statebase
  files:
  - "none*"
  format: binary
  builds:
  - statebase
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
- id: ctrfyle
  files:
  - "none*"
  format: binary
  builds:
  - ctrfyle
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
- id: tunnel-agent
  files:
  - "none*"
  format: binary
  builds:
  - tunnel-agent
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/bhojpur/dcp:{{ .Tag }}"
    extra_files:
    - README.md
