apiVersion: unit.bhojpur.net/v1alpha1
kind: NodePool
metadata:
  name: np2
spec:
  type: Edge 
  annotations:
    foo: bar
  labels:
    foo: bar
  taints:
  - key: foo
    value: bar
    effect: NoSchedule