---
apiVersion: apiregistration.bhojpur.net/v1
kind: APIService
metadata:
  name: v1beta1.metrics.bhojpur.net
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.bhojpur.net
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100