apiVersion: rbac.authorization.bhojpur.net/v1
kind: ClusterRole
metadata:
  name: bhojpur-cloud-controller-manager
rules:
- apiGroups:
  - coordination.bhojpur.net
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.bhojpur.net/v1
kind: ClusterRoleBinding
metadata:
  name: bhojpur-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.bhojpur.net
  kind: ClusterRole
  name: bhojpur-cloud-controller-manager
subjects:
- kind: User
  name: bhojpur-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.bhojpur.net/v1
kind: ClusterRoleBinding
metadata:
  name: bhojpur-cloud-controller-manager-auth-delegator
roleRef:
  apiGroup: rbac.authorization.bhojpur.net
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: User
  name: bhojpur-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.bhojpur.net/v1
kind: RoleBinding
metadata:
  name: bhojpur-cloud-controller-manager-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.bhojpur.net
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: User
  name: bhojpur-cloud-controller-manager
  namespace: kube-system