apiVersion: rbac.authorization.bhojpur.net/v1
kind: ClusterRoleBinding
metadata:
  name: kube-apiserver-kubelet-admin
roleRef:
  apiGroup: rbac.authorization.bhojpur.net
  kind: ClusterRole
  name: system:kubelet-api-admin
subjects:
- apiGroup: rbac.authorization.bhojpur.net
  kind: User
  name: kube-apiserver

---
apiVersion: rbac.authorization.bhojpur.net/v1
kind: ClusterRole
metadata:
  name: system:dcp-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - "networking.bhojpur.net"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  verbs:
  - list
  - get
  - watch

---
apiVersion: rbac.authorization.bhojpur.net/v1
kind: ClusterRoleBinding
metadata:
  name: system:dcp-controller
roleRef:
  apiGroup: rbac.authorization.bhojpur.net
  kind: ClusterRole
  name: system:dcp-controller
subjects:
  - apiGroup: rbac.authorization.bhojpur.net
    kind: User
    name: system:dcp-controller