// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// NodePoolListerExpansion allows custom methods to be added to
// NodePoolLister.
type NodePoolListerExpansion interface{}

// UnitedDeploymentListerExpansion allows custom methods to be added to
// UnitedDeploymentLister.
type UnitedDeploymentListerExpansion interface{}

// UnitedDeploymentNamespaceListerExpansion allows custom methods to be added to
// UnitedDeploymentNamespaceLister.
type UnitedDeploymentNamespaceListerExpansion interface{}

// AppDaemonListerExpansion allows custom methods to be added to
// DcpAppDaemonLister.
type AppDaemonListerExpansion interface{}

// AppDaemonNamespaceListerExpansion allows custom methods to be added to
// DcpAppDaemonNamespaceLister.
type AppDaemonNamespaceListerExpansion interface{}

// IngressListerExpansion allows custom methods to be added to
// DcpIngressLister.
type IngressListerExpansion interface{}