// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

import (
	v1alpha1 "github.com/bhojpur/dcp/pkg/appmanager/apis/apps/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// UnitedDeploymentLister helps list UnitedDeployments.
// All objects returned here must be treated as read-only.
type UnitedDeploymentLister interface {
	// List lists all UnitedDeployments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.UnitedDeployment, err error)
	// UnitedDeployments returns an object that can list and get UnitedDeployments.
	UnitedDeployments(namespace string) UnitedDeploymentNamespaceLister
	UnitedDeploymentListerExpansion
}

// unitedDeploymentLister implements the UnitedDeploymentLister interface.
type unitedDeploymentLister struct {
	indexer cache.Indexer
}

// NewUnitedDeploymentLister returns a new UnitedDeploymentLister.
func NewUnitedDeploymentLister(indexer cache.Indexer) UnitedDeploymentLister {
	return &unitedDeploymentLister{indexer: indexer}
}

// List lists all UnitedDeployments in the indexer.
func (s *unitedDeploymentLister) List(selector labels.Selector) (ret []*v1alpha1.UnitedDeployment, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.UnitedDeployment))
	})
	return ret, err
}

// UnitedDeployments returns an object that can list and get UnitedDeployments.
func (s *unitedDeploymentLister) UnitedDeployments(namespace string) UnitedDeploymentNamespaceLister {
	return unitedDeploymentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// UnitedDeploymentNamespaceLister helps list and get UnitedDeployments.
// All objects returned here must be treated as read-only.
type UnitedDeploymentNamespaceLister interface {
	// List lists all UnitedDeployments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.UnitedDeployment, err error)
	// Get retrieves the UnitedDeployment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.UnitedDeployment, error)
	UnitedDeploymentNamespaceListerExpansion
}

// unitedDeploymentNamespaceLister implements the UnitedDeploymentNamespaceLister
// interface.
type unitedDeploymentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all UnitedDeployments in the indexer for a given namespace.
func (s unitedDeploymentNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.UnitedDeployment, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.UnitedDeployment))
	})
	return ret, err
}

// Get retrieves the UnitedDeployment from the indexer for a given namespace and name.
func (s unitedDeploymentNamespaceLister) Get(name string) (*v1alpha1.UnitedDeployment, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("uniteddeployment"), name)
	}
	return obj.(*v1alpha1.UnitedDeployment), nil
}