// Code generated by client-gen. DO NOT EDIT.

package fake

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

import (
	"context"

	v1alpha1 "github.com/bhojpur/dcp/pkg/appmanager/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppDaemons implements AppDaemonInterface
type FakeAppDaemons struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var dcpappdaemonsResource = schema.GroupVersionResource{Group: "apps.bhojpur.net", Version: "v1alpha1", Resource: "dcpappdaemons"}

var dcpappdaemonsKind = schema.GroupVersionKind{Group: "apps.bhojpur.net", Version: "v1alpha1", Kind: "DcpAppDaemon"}

// Get takes name of the dcpAppDaemon, and returns the corresponding dcpAppDaemon object, and an error if there is any.
func (c *FakeAppDaemons) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DcpAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dcpappdaemonsResource, c.ns, name), &v1alpha1.DcpAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DcpAppDaemon), err
}

// List takes label and field selectors, and returns the list of DcpAppDaemons that match those selectors.
func (c *FakeAppDaemons) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DcpAppDaemonList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dcpappdaemonsResource, dcpappdaemonsKind, c.ns, opts), &v1alpha1.DcpAppDaemonList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DcpAppDaemonList{ListMeta: obj.(*v1alpha1.DcpAppDaemonList).ListMeta}
	for _, item := range obj.(*v1alpha1.DcpAppDaemonList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dcpAppDaemons.
func (c *FakeAppDaemons) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dcpappdaemonsResource, c.ns, opts))

}

// Create takes the representation of a dcpAppDaemon and creates it.  Returns the server's representation of the dcpAppDaemon, and an error, if there is any.
func (c *FakeAppDaemons) Create(ctx context.Context, dcpAppDaemon *v1alpha1.DcpAppDaemon, opts v1.CreateOptions) (result *v1alpha1.DcpAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dcpappdaemonsResource, c.ns, dcpAppDaemon), &v1alpha1.DcpAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DcpAppDaemon), err
}

// Update takes the representation of a dcpAppDaemon and updates it. Returns the server's representation of the dcpAppDaemon, and an error, if there is any.
func (c *FakeAppDaemons) Update(ctx context.Context, dcpAppDaemon *v1alpha1.DcpAppDaemon, opts v1.UpdateOptions) (result *v1alpha1.DcpAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dcpappdaemonsResource, c.ns, dcpAppDaemon), &v1alpha1.DcpAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DcpAppDaemon), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAppDaemons) UpdateStatus(ctx context.Context, dcpAppDaemon *v1alpha1.DcpAppDaemon, opts v1.UpdateOptions) (*v1alpha1.DcpAppDaemon, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dcpappdaemonsResource, "status", c.ns, dcpAppDaemon), &v1alpha1.DcpAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DcpAppDaemon), err
}

// Delete takes name of the dcpAppDaemon and deletes it. Returns an error if one occurs.
func (c *FakeAppDaemons) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dcpappdaemonsResource, c.ns, name), &v1alpha1.DcpAppDaemon{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppDaemons) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dcpappdaemonsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DcpAppDaemonList{})
	return err
}

// Patch applies the patch and returns the patched dcpAppDaemon.
func (c *FakeAppDaemons) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DcpAppDaemon, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dcpappdaemonsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DcpAppDaemon{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DcpAppDaemon), err
}