#!/bin/bash
set -e
set -x

REPO="https://api.github.com/repos/bhojpur/dcp-upgrade/dispatches"

# send dispatch event to REPO
curl -XPOST -u "${PAT_USERNAME}:${PAT_TOKEN}" \
        -H "Accept: application/vnd.github.everest-preview+json"  \
        -H "Content-Type: application/json" $REPO \
        --data '{"event_type": "create_tag", "client_payload": {"tag":"'"$DRONE_TAG"'"}}'

SYSTEM_AGENT_INSTALLER_DCP_REPO="https://api.github.com/repos/bhojpur/system-agent-installer-dcp/dispatches"

# send dispatch event to SYSTEM_AGENT_INSTALLER_DCP_REPO
curl -XPOST -u "${PAT_USERNAME}:${PAT_TOKEN}" \
        -H "Accept: application/vnd.github.everest-preview+json"  \
        -H "Content-Type: application/json" $SYSTEM_AGENT_INSTALLER_DCP_REPO \
        --data '{"event_type": "create_tag", "client_payload": {"tag":"'"$DRONE_TAG"'"}}'