#!/bin/bash
set -e -x

cd $(dirname $0)/..

. ./scripts/version.sh

GO=${GO-go}

for i in crictl kubectl dcp-agent dcp-server dcp-etcd-snapshot dcp-secrets-encrypt dcp-certificate; do
    rm -f bin/$i
    ln -s dcp bin/$i
done

for i in bridge flannel host-local loopback portmap; do
    rm -f bin/$i
    ln -s cni bin/$i
done

cp contrib/util/check-config.sh bin/check-config

rm -rf build/data
mkdir -p build/data build/out
mkdir -p dist/artifacts

(
    set +x
    cd bin
    find . -not -path '*/\.*' -type f -exec sha256sum {} \; | sed -e 's| \./| |' | sort -k2 >.sha256sums
    (
        for f in $(find . -type l); do
            echo $f $(readlink $f)
        done
    ) | sed -e 's|^\./||' | sort >.links
    set -x
)

tar cvf ./build/out/data.tar ./bin ./etc
zstd --no-progress -T0 -16 -f --long=25 --rm ./build/out/data.tar -o ./build/out/data.tar.zst
HASH=$(sha256sum ./build/out/data.tar.zst | awk '{print $1}')

cp ./build/out/data.tar.zst ./build/data/${HASH}.tar.zst

BIN_SUFFIX="-${ARCH}"
if [ ${ARCH} = amd64 ]; then
    BIN_SUFFIX=""
elif [ ${ARCH} = arm ]; then
    BIN_SUFFIX="-armhf"
fi

CMD_NAME=dist/artifacts/dcp${BIN_SUFFIX}

"${GO}" generate
LDFLAGS="
    -X github.com/bhojpur/dcp/pkg/cloud/version.Version=$VERSION
    -X github.com/bhojpur/dcp/pkg/cloud/version.GitCommit=${COMMIT:0:8}
    -w -s
"
STATIC="-extldflags '-static'"
CGO_ENABLED=0 "${GO}" build -ldflags "$LDFLAGS $STATIC" -o ${CMD_NAME} ./cmd/cloud/dcp/main.go

stat ${CMD_NAME}

./scripts/build-upload ${CMD_NAME} ${COMMIT}