apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: dcp-app-manager
  name: manager-metrics-service
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: dcp-app-manager