apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dcpsvr
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
  - apiGroups:
      - apps.bhojpur.net
    resources:
      - nodepools
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - dcpsvr-cfg
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dcpsvr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dcpsvr
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:nodes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dcpsvr-cfg
  namespace: kube-system
data:
  cache_agents: ""