apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: dcp-tunnel-server
rules:
- apiGroups:
    - certificates.k8s.io
  resources:
    - certificatesigningrequests
  verbs:
    - create
    - get
    - list
    - watch
- apiGroups:
    - certificates.k8s.io
  resources:
    - certificatesigningrequests/approval
  verbs:
    - update
- apiGroups:
    - certificates.k8s.io
  resourceNames:
    - kubernetes.io/legacy-unknown
  resources:
    - signers
  verbs:
    - approve
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
  - create
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
  - get
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dcp-tunnel-server
subjects:
  - kind: ServiceAccount
    name: dcp-tunnel-server
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: dcp-tunnel-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcp-tunnel-server
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: x-tunnel-server-svc
  namespace: kube-system
  labels:
    name: dcp-tunnel-server
spec:
  type: NodePort
  ports:
  - port: 10263
    targetPort: 10263
    name: https
  - port: 10262
    targetPort: 10262
    name: tcp
  selector:
    k8s-app: dcp-tunnel-server
---
apiVersion: v1
kind: Service
metadata:
  name: x-tunnel-server-internal-svc
  namespace: kube-system
  labels:
    name: dcp-tunnel-server
spec:
  ports:
    - port: 10250
      targetPort: 10263
      name: https
    - port: 10255
      targetPort: 10264
      name: http
  selector:
    k8s-app: dcp-tunnel-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dcp-tunnel-server-cfg
  namespace: kube-system
data:
  localhost-proxy-ports: "10266, 10267"
  http-proxy-ports: ""
  https-proxy-ports: ""
  dnat-ports-pair: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcp-tunnel-server
  namespace: kube-system
  labels:
    k8s-app: dcp-tunnel-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dcp-tunnel-server
  template:
    metadata:
      labels:
        k8s-app: dcp-tunnel-server
    spec:
      hostNetwork: true
      serviceAccountName: dcp-tunnel-server
      restartPolicy: Always
      volumes:
      - name: tunnel-server-dir
        hostPath:
          path: /var/lib/tunnel-server
          type: DirectoryOrCreate
      tolerations:
      - operator: "Exists"
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
        bhojpur.net/is-edge-worker: "false"
      containers:
      - name: dcp-tunnel-server
        image: bhojpur/tunnel-server:latest
        imagePullPolicy: IfNotPresent
        command:
        - tunnel-server
        args:
        - --bind-address=$(NODE_IP)
        - --insecure-bind-address=$(NODE_IP)
        - --proxy-strategy=destHost
        - --v=2
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
        - name: tunnel-server-dir
          mountPath: /var/lib/tunnel-server